config/routes.rb
Rails.application.routes.draw do
  resources :devils
  resources :tempers
  resources :elements
  resources :ideologies
  resources :answers
  resources :surveys
  resources :questions
  resources :users

end

app/models/ideology.rb
class Ideology < ActiveRecord::Base
  has_many :users
  def self.judge(a,b,c,d)
    if a>= 0 then ta=1 else ta=-1 end
    if b>= 0 then tb=1 else tb=-1 end
    if c>= 0 then tc=1 else tc=-1 end
    if d>= 0 then td=1 else td=-1 end
    where("\"A\" = ? and \"B\" = ? and \"C\" = ? and \"D\" = ?",ta,tb,tc,td)
  end
end

app/controllers/ideologies_controller.rb
class IdeologiesController < ApplicationController
  before_action :set_ideology, only: [:show, :edit, :update, :destroy]

  # GET /ideologies
  # GET /ideologies.json
  def index
    @ideologies = Ideology.all
  end

  # GET /ideologies/1
  # GET /ideologies/1.json
  def show
  end

  # GET /ideologies/new
  def new
    @ideology = Ideology.new
  end

  # GET /ideologies/1/edit
  def edit
  end

  # POST /ideologies
  # POST /ideologies.json
  def create
    @ideology = Ideology.new(ideology_params)

    respond_to do |format|
      if @ideology.save
        format.html { redirect_to @ideology, notice: 'Ideology was successfully created.' }
        format.json { render :show, status: :created, location: @ideology }
      else
        format.html { render :new }
        format.json { render json: @ideology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideologies/1
  # PATCH/PUT /ideologies/1.json
  def update
    respond_to do |format|
      if @ideology.update(ideology_params)
        format.html { redirect_to @ideology, notice: 'Ideology was successfully updated.' }
        format.json { render :show, status: :ok, location: @ideology }
      else
        format.html { render :edit }
        format.json { render json: @ideology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideologies/1
  # DELETE /ideologies/1.json
  def destroy
    @ideology.destroy
    respond_to do |format|
      format.html { redirect_to ideologies_url, notice: 'Ideology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ideology
      @ideology = Ideology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ideology_params
      params.require(:ideology).permit(:name, :A, :B, :C, :D, :note, :NoteA, :NoteB, :NoteC, :NoteD)
    end
end

app/helpers/ideologies_helper.rb
module IdeologiesHelper
end

app/views/ideologies/_form.html.erb
<%= form_for(@ideology) do |f| %>
  <% if @ideology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ideology.errors.count, "error") %> prohibited this ideology from being saved:</h2>

      <ul>
      <% @ideology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :A %><br>
    <%= f.number_field :A %>
  </div>
  <div class="field">
    <%= f.label :B %><br>
    <%= f.number_field :B %>
  </div>
  <div class="field">
    <%= f.label :C %><br>
    <%= f.number_field :C %>
  </div>
  <div class="field">
    <%= f.label :D %><br>
    <%= f.number_field :D %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :NoteA %><br>
    <%= f.text_area :NoteA %>
  </div>
  <div class="field">
    <%= f.label :NoteB %><br>
    <%= f.text_area :NoteB %>
  </div>
  <div class="field">
    <%= f.label :NoteC %><br>
    <%= f.text_area :NoteC %>
  </div>
  <div class="field">
    <%= f.label :NoteD %><br>
    <%= f.text_area :NoteD %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideologies/edit.html.erb
<h1>Editing Ideology</h1>

<%= render 'form' %>

<%= link_to 'Show', @ideology %> |
<%= link_to 'Back', ideologies_path %>

app/views/ideologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideologies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideologies.each do |ideology| %>
      <tr>
        <td><%= ideology.name %></td>
        <td><%= ideology.A %></td>
        <td><%= ideology.B %></td>
        <td><%= ideology.C %></td>
        <td><%= ideology.D %></td>
        <td><%= ideology.note %></td>
        <td><%= link_to 'Show', ideology %></td>
        <td><%= link_to 'Edit', edit_ideology_path(ideology) %></td>
        <td><%= link_to 'Destroy', ideology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ideology', new_ideology_path %>

app/views/ideologies/new.html.erb
<h1>New Ideology</h1>

<%= render 'form' %>

<%= link_to 'Back', ideologies_path %>

app/views/ideologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ideology.name %>
</p>

<p>
  <strong>A:</strong>
  <%= @ideology.A %>
</p>

<p>
  <strong>B:</strong>
  <%= @ideology.B %>
</p>

<p>
  <strong>C:</strong>
  <%= @ideology.C %>
</p>

<p>
  <strong>D:</strong>
  <%= @ideology.D %>
</p>
<p>
  <strong>Note:</strong>
  <%= @ideology.note %>
</p>


<%= link_to 'Edit', edit_ideology_path(@ideology) %> |
<%= link_to 'Back', ideologies_path %>