config/routes.rb
Rails.application.routes.draw do
  resources :devils
  resources :tempers
  resources :elements
  resources :ideologies
  resources :answers
  resources :surveys
  resources :questions
  resources :users

end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @questions = Question.all
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:q01, :q02, :q03, :q04, :q05, :q06, :q07, :q08, :q09, :q10, :q11, :q12, :q13, :q14, :q15, :q16, :A, :B, :C, :D, :result)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% @questions.each_with_index do |question,i| %>
  <%= question.name %></br>
  <div class="field">
    <%= f.label ("q" + format("%02d",i+1)).to_sym%><br>
    <%= f.number_field ("q" +format("%02d",i+1)).to_sym %>
  </div>
<% end %>

  <div class="field">
    <%= f.label :A %><br>
    <%= f.number_field :A %>
  </div>
  <div class="field">
    <%= f.label :B %><br>
    <%= f.number_field :B %>
  </div>
  <div class="field">
    <%= f.label :C %><br>
    <%= f.number_field :C %>
  </div>
  <div class="field">
    <%= f.label :D %><br>
    <%= f.number_field :D %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Q01</th>
      <th>Q02</th>
      <th>Q03</th>
      <th>Q04</th>
      <th>Q05</th>
      <th>Q06</th>
      <th>Q07</th>
      <th>Q08</th>
      <th>Q09</th>
      <th>Q10</th>
      <th>Q11</th>
      <th>Q12</th>
      <th>Q13</th>
      <th>Q14</th>
      <th>Q15</th>
      <th>Q16</th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.q01 %></td>
        <td><%= survey.q02 %></td>
        <td><%= survey.q03 %></td>
        <td><%= survey.q04 %></td>
        <td><%= survey.q05 %></td>
        <td><%= survey.q06 %></td>
        <td><%= survey.q07 %></td>
        <td><%= survey.q08 %></td>
        <td><%= survey.q09 %></td>
        <td><%= survey.q10 %></td>
        <td><%= survey.q11 %></td>
        <td><%= survey.q12 %></td>
        <td><%= survey.q13 %></td>
        <td><%= survey.q14 %></td>
        <td><%= survey.q15 %></td>
        <td><%= survey.q16 %></td>
        <td><%= survey.A %></td>
        <td><%= survey.B %></td>
        <td><%= survey.C %></td>
        <td><%= survey.D %></td>
        <td><%= survey.result %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q01:</strong>
  <%= @survey.q01 %>
</p>

<p>
  <strong>Q02:</strong>
  <%= @survey.q02 %>
</p>

<p>
  <strong>Q03:</strong>
  <%= @survey.q03 %>
</p>

<p>
  <strong>Q04:</strong>
  <%= @survey.q04 %>
</p>

<p>
  <strong>Q05:</strong>
  <%= @survey.q05 %>
</p>

<p>
  <strong>Q06:</strong>
  <%= @survey.q06 %>
</p>

<p>
  <strong>Q07:</strong>
  <%= @survey.q07 %>
</p>

<p>
  <strong>Q08:</strong>
  <%= @survey.q08 %>
</p>

<p>
  <strong>Q09:</strong>
  <%= @survey.q09 %>
</p>

<p>
  <strong>Q10:</strong>
  <%= @survey.q10 %>
</p>

<p>
  <strong>Q11:</strong>
  <%= @survey.q11 %>
</p>

<p>
  <strong>Q12:</strong>
  <%= @survey.q12 %>
</p>

<p>
  <strong>Q13:</strong>
  <%= @survey.q13 %>
</p>

<p>
  <strong>Q14:</strong>
  <%= @survey.q14 %>
</p>

<p>
  <strong>Q15:</strong>
  <%= @survey.q15 %>
</p>

<p>
  <strong>Q16:</strong>
  <%= @survey.q16 %>
</p>

<p>
  <strong>A:</strong>
  <%= @survey.A %>
</p>

<p>
  <strong>B:</strong>
  <%= @survey.B %>
</p>

<p>
  <strong>C:</strong>
  <%= @survey.C %>
</p>

<p>
  <strong>D:</strong>
  <%= @survey.D %>
</p>

<p>
  <strong>Result:</strong>
  <%= @survey.result %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>